-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAskVeRT/QivbKd8U
oZG5QuoyEC1moDcij/67pGPiZ0igCgYIKoZIzj0DAQehRANCAAS/OyUSm1OP3sun
tZlZKHMzcsXbxzVvYMMZ+WjwVcaOK+9FFR3UjuJeal3saRi2ejJjJa3qSU2u43iI
GcGEsfqj
-----END PRIVATE KEY-----